aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*brick*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*stone*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*moss*Albedo.jpg"
#aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*surface*Albedo.jpg"
aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*leave*Albedo.jpg"
aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*rock*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*street*Albedo.jpg"
aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*tile*Albedo.jpg"
aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*floor*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*fabric*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*debris*Albedo.jpg"

# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Brick*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Stone*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Moss*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Surface*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Leave*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Rock*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Street*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Tile*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Floor*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Fabric*Albedo.jpg"
# aws s3 cp s3://biglook/ ./dataset/biglook --recursive --exclude "*" --include "*Debris*Albedo.jpg"