# This is a basic workflow to help you get started with Actions

name: Test Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Show ASCII greeting
        uses: mscoutermarsh/ascii-art-action@master
        with:
          text: 'Test Workflow!'

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install PyTorch
        run: |
          python -m pip install --upgrade pip
          # Install CPU-based pytorch
          pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
          # Maybe use the CUDA 10.2 version instead?
          # pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html

      - name: Install other dependencies
        run: |
          chmod +x ./scripts/devscripts/install_deps.sh
          ./scripts/devscripts/install_deps.sh "install_deps"
        shell: bash

      - name: Open issue on failure
        if: ${{ failure() }}
        uses: rishabhgupta/git-action-issue@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: CI/CD failed
          body: Commit ${{ github.sha }} daily scheduled [CI run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed, please looki into it.
          assignees: 'haochen23'


